export const JWT_SECRET = 'JWT_SECRET';
export const JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';
export const JWT_ACCESS_EXPIRATION = 'JWT_ACCESS_EXPIRATION';
export const JWT_REFRESH_EXPIRATION_DAYS = 'JWT_REFRESH_EXPIRATION_DAYS';
